---
# Source: nfs-client-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
  name: v3.1.0-k8s1.11-nfs-client-provisioner
---
# Source: nfs-client-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
  name: nfs-client
provisioner: cluster.local/v3.1.0-k8s1.11-nfs-client-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"
---
# Source: nfs-client-provisioner/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
  name: v3.1.0-k8s1.11-nfs-client-provisioner-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
# Source: nfs-client-provisioner/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
  name: run-v3.1.0-k8s1.11-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: v3.1.0-k8s1.11-nfs-client-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: v3.1.0-k8s1.11-nfs-client-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-client-provisioner/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
  name: leader-locking-v3.1.0-k8s1.11-nfs-client-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# Source: nfs-client-provisioner/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
  name: leader-locking-v3.1.0-k8s1.11-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: v3.1.0-k8s1.11-nfs-client-provisioner
    namespace: default
roleRef:
  kind: Role
  name: leader-locking-v3.1.0-k8s1.11-nfs-client-provisioner
  apiGroup: rbac.authorization.k8s.io
---
# Source: nfs-client-provisioner/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v3.1.0-k8s1.11-nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
    chart: nfs-client-provisioner-1.2.11
    heritage: Helm
    release: v3.1.0-k8s1.11
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
      release: v3.1.0-k8s1.11
  template:
    metadata:
      annotations:
      labels:
        app: nfs-client-provisioner
        release: v3.1.0-k8s1.11
    spec:
      serviceAccountName: v3.1.0-k8s1.11-nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: "vikrantsnirban/nfs-client-provisioner:v3.1.0-k8s1.11"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/v3.1.0-k8s1.11-nfs-client-provisioner
            - name: NFS_SERVER
              value: 172.42.42.99
            - name: NFS_PATH
              value: /mnt/nfs_share
      volumes:
        - name: nfs-client-root
          nfs:
            server: 172.42.42.99
            path: /mnt/nfs_share
